fieldLayouts:
  57038148-5c46-43e2-9c5b-9760e04375f2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: serviceIcons
hasUrls: true
name: 'Service Icons'
settings:
  path: '@assetBasePath/site/images/service-icons'
sortOrder: 3
type: craft\volumes\Local
url: '@assetBaseUrl/images/service-icons'
