contentColumnType: string
fieldGroup: 0d0b7e16-8d7c-4d6f-9059-d11c473058f4
handle: featuredThumb
instructions: 'Thumb image for use on home page or archives.'
name: 'Featured Thumb'
searchable: true
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:0193dc64-5499-4e28-95dd-f8f603154851'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:0193dc64-5499-4e28-95dd-f8f603154851'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
